"""
MIT License

Copyright (c) 2020 Alexander Mackay

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
# this python programme plots the stability data generated by compEWM.py
from fenics_base import *

# Parameters
r_a = 1.0 #Journal Radius
r_b = 2.0#1.25 #Bearing Radius
x_1 = -0.80 #-0.2
y_1 = 0.0
x_2 = 0.0
y_2 = 0.0
mesh_resolution = 60
mesh = JBP_mesh(mesh_resolution, x_1, x_2, y_1, y_2, r_a, r_b)

ec = np.sqrt((x_2 - x_1)**2 + (y_2 - y_1)**2)
c = r_b - r_a
ecc = ec/c

mplot(mesh)
plt.scatter([0.50113318, 0.52487454, 0.50113318, 0.72773945], [-0.72143657, -0.65494735, -0.72143657, -0.27908338], marker='x', color="red")
plt.savefig("ewm-stream-function-location-jbp_mesh, resolution"+str(mesh_resolution)+ ", L= "+str(c)+", eccentricity ratio: "+str(ecc)+".eps", format="eps")
plt.clf() 


mplot(mesh)
plt.scatter([0.46963351, 0.46963351, 0.47481062, 0.5389431], [-0.27823149, -0.27823149, -0.31039495, 0.00399524], marker='x', color="red")
plt.savefig("ewm-shear-rate-location-jbp_mesh, resolution"+str(mesh_resolution)+ ", L= "+str(c)+", eccentricity ratio: "+str(ecc)+".eps", format="eps")
plt.clf() 

# Read in vtk file
#W, V, Vd, Z, Zd, Zc, Q, Qt, Qr = function_spaces(mesh, 2)

#p = load_solution("hd5/pressure-solution, Re=100.0, We=0.001, Ma=0.01, t=0.10125000000000006.h5", Q)
#mplot(p)
#plt.scatter([0.50113318, 0.52487454, 0.50113318, 0.72773945], [-0.72143657, -0.65494735, -0.72143657, -0.27908338], marker='o', color="red")
#plt.savefig("ewm-stream-function-location-jbp_pressure, resolution"+str(mesh_resolution)+ ", L= "+str(c)+", eccentricity ratio: "+str(ecc)+".eps", format="eps")
#plt.clf() 
